name: Build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17
          cache: gradle
      - name: Build backend jar and client js
        run: ./gradlew shadowJar unpackSkikoWasmRuntimeJs jsBrowserWebpack
      - name: Run tests
        run: ./gradlew check
      - name: Compress web client files
        run: |
          find js/ -type f | while read file; do
            if [ ! -e "${file}.gz" -o "${file}" -ot "${file}.gz" ]; then
              gzip -9 -k "$file"
            fi
          done
      - name: Archive web client artifacts
        uses: actions/upload-artifact@v3
        with:
          name: mcmapper-web
          path: js/
      - name: Archive backend jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: mcmapper-backend
          path: mcmapper-backend.jar
